### ISSUE TITLE
Adding initial benchmarks

### ISSUE THREAD

**Issue by FranciscoThiesen** [simdjson/experimental_json_builder#3]
Ideas:
- Coming up with a few test instances of different size
- Measure run-time (It would be interesting to compare with the modern C++ json library)

Later:
- Add benchmark for compile-time as well

**Comment by lemire** [comment]
We definitively want to serialize at gigabytes per second. :-)

Note that we may want to rely on `fmt` (which is now part of C++), as it has good performance and is widely available.
