### ISSUE TITLE
Come-up with an initial working implementation for serialization

### ISSUE THREAD

**Issue by FranciscoThiesen** [simdjson/experimental_json_builder#8]
Now that we have some examples/benchmarks, we could test serialization + deserialization with the same examples.

My initial aim is for a simple implementation, which we can iterate upon later (perf, complex use-cases, etc)

**Comment by lemire** [comment]
It *should* be possible to leverage simdjson for deserialization.

**Comment by FranciscoThiesen** [comment]
Marking this as done!
